# Generated by Django 4.2.15 on 2025-10-04 09:21

from django.db import migrations, models
import jeux.models.player


class Migration(migrations.Migration):

    dependencies = [
        ("jeux", "0009_videogame_status_videogame_steam_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="background_file",
            field=models.FileField(
                blank=True, upload_to=jeux.models.player.user_directory_path
            ),
        ),
    ]
