# Generated by Django 4.2.15 on 2025-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeux', '0010_alter_player_background_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='steam_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
